-- V1: the database schema as it was when Flyway was introduced (dumped from PostgreSQL with pg_dump).
-- On the existing database Flyway does NOT run this file: it records it as the "baseline" (already applied).
-- On a brand-new, empty database Flyway runs it to create every table.
-- Never edit this file after it has been applied; add a new V<n>__description.sql file instead.

CREATE TABLE public.customers (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    phone_number character varying(255) NOT NULL
);

ALTER TABLE public.customers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.dish (
    id bigint NOT NULL,
    active boolean,
    category character varying(255),
    cuisine character varying(255),
    description character varying(255),
    name character varying(255) NOT NULL,
    vegetarian boolean
);

ALTER TABLE public.dish ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dish_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.event_type (
    id bigint NOT NULL,
    active boolean,
    description character varying(255),
    name character varying(255) NOT NULL
);

ALTER TABLE public.event_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.event_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.order_policies (
    id bigint NOT NULL,
    cancel_grace_period boolean,
    max_allowed_duration character varying(255),
    modify_orders character varying(255)[],
    vendor_id bigint NOT NULL
);

ALTER TABLE public.order_policies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_policies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.package (
    id bigint NOT NULL,
    active boolean,
    description character varying(255),
    name character varying(255) NOT NULL,
    price numeric(38,2),
    price_unit character varying(255),
    vendor_id bigint NOT NULL
);

CREATE TABLE public.package_dish (
    id bigint NOT NULL,
    quantity integer,
    dish_id bigint,
    package_id bigint
);

ALTER TABLE public.package_dish ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.package_dish_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.package ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.package_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.required_item (
    id bigint NOT NULL,
    active boolean,
    description character varying(255),
    name character varying(255) NOT NULL,
    unit character varying(255)
);

ALTER TABLE public.required_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.required_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.vendor_bank_detail (
    id bigint NOT NULL,
    account_holder_name character varying(255) NOT NULL,
    account_number character varying(255) NOT NULL,
    ifsc_code character varying(255) NOT NULL,
    vendor_id bigint NOT NULL
);

ALTER TABLE public.vendor_bank_detail ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vendor_bank_detail_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.vendor_buissness_information (
    id bigint NOT NULL,
    fssai_number character varying(255) NOT NULL,
    gst_number character varying(255) NOT NULL,
    location_address character varying(255) NOT NULL,
    contact_number character varying(255) NOT NULL,
    buissness_name character varying(255) NOT NULL,
    years_of_buissness integer NOT NULL,
    vendor_id bigint NOT NULL
);

ALTER TABLE public.vendor_buissness_information ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vendor_buissness_information_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.vendor_dish (
    id bigint NOT NULL,
    available boolean,
    price numeric(38,2),
    dish_id bigint,
    vendor_id bigint
);

ALTER TABLE public.vendor_dish ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vendor_dish_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.vendor_media (
    id bigint NOT NULL,
    image character varying(255) NOT NULL,
    video character varying(255) NOT NULL,
    vendor_id bigint NOT NULL
);

ALTER TABLE public.vendor_media ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vendor_media_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.vendor_payment_plan (
    id bigint NOT NULL,
    advance_payment character varying(255) NOT NULL,
    post_payment character varying(255) NOT NULL,
    pre_payment character varying(255) NOT NULL,
    vendor_id bigint NOT NULL
);

ALTER TABLE public.vendor_payment_plan ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vendor_payment_plan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.vendor_service_area (
    id bigint NOT NULL,
    max_people bigint,
    maximum_order_size bigint NOT NULL,
    minimum_order_value bigint NOT NULL,
    minimum_order_size bigint NOT NULL,
    order_size bigint NOT NULL,
    service_city character varying(255) NOT NULL,
    service_country character varying(255) NOT NULL,
    service_pin character varying(255) NOT NULL,
    vendor_id bigint NOT NULL,
    CONSTRAINT vendor_service_area_max_people_check CHECK ((max_people <= 1000)),
    CONSTRAINT vendor_service_area_maximum_order_size_check CHECK ((maximum_order_size <= 1000)),
    CONSTRAINT vendor_service_area_minimum_order_size_check CHECK ((minimum_order_size >= 200)),
    CONSTRAINT vendor_service_area_minimum_order_value_check CHECK ((minimum_order_value >= 250))
);

ALTER TABLE public.vendor_service_area ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vendor_service_area_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.vendorprofile (
    id bigint NOT NULL,
    vendor_address character varying(255) NOT NULL,
    vendor_name character varying(255) NOT NULL,
    vendor_id bigint
);

ALTER TABLE public.vendorprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vendorprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.vendors (
    id bigint NOT NULL,
    email character varying(255),
    password character varying(255),
    phone character varying(255),
    role character varying(255),
    CONSTRAINT vendors_role_check CHECK (((role)::text = ANY ((ARRAY['VENDOR'::character varying, 'ADMIN'::character varying])::text[])))
);

ALTER TABLE public.vendors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vendors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.dish
    ADD CONSTRAINT dish_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.event_type
    ADD CONSTRAINT event_type_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.order_policies
    ADD CONSTRAINT order_policies_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.package_dish
    ADD CONSTRAINT package_dish_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.package
    ADD CONSTRAINT package_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.required_item
    ADD CONSTRAINT required_item_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.vendor_bank_detail
    ADD CONSTRAINT uk2vm442vi7g6tt6q4meqkg3u8x UNIQUE (vendor_id);

ALTER TABLE ONLY public.vendor_payment_plan
    ADD CONSTRAINT uk46vpl9q8xy4an3joidaphwkwo UNIQUE (vendor_id);

ALTER TABLE ONLY public.vendor_buissness_information
    ADD CONSTRAINT uk63gx889798tiipgs3aaqhmspa UNIQUE (vendor_id);

ALTER TABLE ONLY public.vendors
    ADD CONSTRAINT uk8xmc0rpdougqaftbgr1s2tolo UNIQUE (email);

ALTER TABLE ONLY public.vendors
    ADD CONSTRAINT uka9lqvsj1d6b8no33krte95i0h UNIQUE (phone);

ALTER TABLE ONLY public.vendor_service_area
    ADD CONSTRAINT ukdb0jqsb5mq4oxaqh9sjb6d16b UNIQUE (vendor_id);

ALTER TABLE ONLY public.event_type
    ADD CONSTRAINT ukdunk58vf3o8hxdjjspls1jrl UNIQUE (name);

ALTER TABLE ONLY public.order_policies
    ADD CONSTRAINT ukhr0jq7ublcdwud9cnwyktc4jo UNIQUE (vendor_id);

ALTER TABLE ONLY public.vendorprofile
    ADD CONSTRAINT ukifata65rnaf4qrt73dsy72jch UNIQUE (vendor_id);

ALTER TABLE ONLY public.vendor_media
    ADD CONSTRAINT ukpcvtd3tq12dqjfn68mycb00kw UNIQUE (vendor_id);

ALTER TABLE ONLY public.vendor_bank_detail
    ADD CONSTRAINT vendor_bank_detail_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.vendor_buissness_information
    ADD CONSTRAINT vendor_buissness_information_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.vendor_dish
    ADD CONSTRAINT vendor_dish_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.vendor_media
    ADD CONSTRAINT vendor_media_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.vendor_payment_plan
    ADD CONSTRAINT vendor_payment_plan_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.vendor_service_area
    ADD CONSTRAINT vendor_service_area_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.vendorprofile
    ADD CONSTRAINT vendorprofile_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.vendors
    ADD CONSTRAINT vendors_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.package_dish
    ADD CONSTRAINT fk1n8uxnjloivjltv65eylx2t8t FOREIGN KEY (dish_id) REFERENCES public.dish(id);

ALTER TABLE ONLY public.package
    ADD CONSTRAINT fk3d0jv3a2x1ydifs9emjp5ivna FOREIGN KEY (vendor_id) REFERENCES public.vendors(id);

ALTER TABLE ONLY public.vendor_service_area
    ADD CONSTRAINT fk49arecbcg08l87axc6bg8t9ep FOREIGN KEY (vendor_id) REFERENCES public.vendorprofile(id);

ALTER TABLE ONLY public.vendor_dish
    ADD CONSTRAINT fk9qvjl45ss96wlglr5fo7sr8i3 FOREIGN KEY (dish_id) REFERENCES public.dish(id);

ALTER TABLE ONLY public.vendorprofile
    ADD CONSTRAINT fkd1hfh2djgige3ytil3al20csq FOREIGN KEY (vendor_id) REFERENCES public.vendors(id);

ALTER TABLE ONLY public.vendor_payment_plan
    ADD CONSTRAINT fkdjvewkgrrd8pgc3gmux9iy230 FOREIGN KEY (vendor_id) REFERENCES public.vendorprofile(id);

ALTER TABLE ONLY public.package_dish
    ADD CONSTRAINT fkdltaheeme1m8yvjmaen2hpyio FOREIGN KEY (package_id) REFERENCES public.package(id);

ALTER TABLE ONLY public.vendor_bank_detail
    ADD CONSTRAINT fkdq2g2e1b8ddcnw1r9pp8vbntm FOREIGN KEY (vendor_id) REFERENCES public.vendorprofile(id);

ALTER TABLE ONLY public.vendor_buissness_information
    ADD CONSTRAINT fke9v5njfjue8babm136j4uw4k3 FOREIGN KEY (vendor_id) REFERENCES public.vendorprofile(id);

ALTER TABLE ONLY public.order_policies
    ADD CONSTRAINT fkhiicn146bnd4iyyeb56dn9aqt FOREIGN KEY (vendor_id) REFERENCES public.vendorprofile(id);

ALTER TABLE ONLY public.vendor_dish
    ADD CONSTRAINT fksrh3u0y02tilw9qadak1rt0qo FOREIGN KEY (vendor_id) REFERENCES public.vendors(id);

ALTER TABLE ONLY public.vendor_media
    ADD CONSTRAINT fkt56o0l4i6s8xsega08w7hcl82 FOREIGN KEY (vendor_id) REFERENCES public.vendorprofile(id);
